# Generated by Django 6.0 on 2026-02-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacion',
            options={'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='usuarioorganizacion',
            options={'verbose_name': 'Usuario Organización', 'verbose_name_plural': 'Usuarios Organizaciones'},
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='base_datos_creada',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='db_name',
        ),
    ]
