# Generated by Django 6.0 on 2026-02-22 22:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_organizacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('coste_adulto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coste_menor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name_plural': '03 · Actividades',
            },
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': '09 · Comunicaciones',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('adulto', 'Adulto'), ('menor', 'Menor')], max_length=10, unique=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': '08 · Contactos',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='inventario/')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
            },
        ),
        migrations.CreateModel(
            name='TipoComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de comunicación',
                'verbose_name_plural': 'Tipos de comunicación',
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de contacto',
                'verbose_name_plural': 'Tipos de contacto',
            },
        ),
        migrations.CreateModel(
            name='ArchivoComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='comunicaciones/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('comunicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='asociaciones.comunicacion')),
            ],
            options={
                'verbose_name': 'Archivo de comunicación',
                'verbose_name_plural': 'Archivos de comunicación',
            },
        ),
        migrations.CreateModel(
            name='ArchivoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='contactos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='asociaciones.contacto')),
            ],
            options={
                'verbose_name': 'Archivo de contacto',
                'verbose_name_plural': 'Archivos de contacto',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('tipo', models.CharField(choices=[('anual', 'Anual'), ('extraordinaria', 'Extraordinaria')], default='anual', max_length=20)),
                ('importe_adulto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('importe_menor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion')),
            ],
            options={
                'verbose_name': 'familia',
                'verbose_name_plural': 'familias',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('bizum', 'Bizum')], default='efectivo', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='gastos/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='asociaciones.actividad')),
            ],
            options={
                'verbose_name_plural': '06 · Gastos',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('importe_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='asociaciones.actividad')),
            ],
            options={
                'verbose_name_plural': '04 · Inscripciones',
            },
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones', to='asociaciones.organismo'),
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('nombre_contacto', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('aportacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('año', models.PositiveIntegerField()),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='patrocinadores/')),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(blank=True, help_text='Dejar vacío si el patrocinio es general', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrocinadores', to='asociaciones.actividad')),
            ],
            options={
                'verbose_name_plural': '07 · Patrocinadores',
            },
        ),
        migrations.CreateModel(
            name='Patrocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('aportacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('año', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrocinios', to='asociaciones.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Socio activo')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('en_whatsapp', models.BooleanField(default=False)),
                ('es_colaborador', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('proteccion_datos', models.BooleanField(default=False)),
                ('acepta_fotografias', models.BooleanField(default=False)),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asociaciones.familia')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion')),
            ],
            options={
                'verbose_name_plural': '01 · Socios',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('bizum', 'Bizum')], max_length=20)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='asociaciones.actividad')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asociaciones.cuota')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asociaciones.familia')),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asociaciones.inscripcion')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='asociaciones.socio')),
            ],
            options={
                'verbose_name_plural': '05 · Pagos',
            },
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='asociaciones.socio'),
        ),
        migrations.CreateModel(
            name='CuotaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='asociaciones.cuota')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_generadas', to='asociaciones.socio')),
            ],
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones', to='asociaciones.tipocomunicacion'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='asociaciones.tipocontacto'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'anual')), fields=('organizacion', 'tipo', 'año'), name='unique_anual_por_año'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('actividad', 'socio')},
        ),
        migrations.AlterUniqueTogether(
            name='cuotasocio',
            unique_together={('socio', 'cuota')},
        ),
    ]
