# Generated by Django 6.0 on 2026-02-23 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones', '0001_initial'),
        ('core', '0002_alter_organizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='organizacion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
            preserve_default=False,
        ),
    ]
