# Generated by Django 6.0 on 2026-02-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones', '0002_actividad_organizacion'),
        ('core', '0002_alter_organizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={},
        ),
        migrations.AddField(
            model_name='pago',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
            preserve_default=False,
        ),
    ]
