# Generated by Django 6.0 on 2026-03-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones', '0003_alter_inscripcion_options_pago_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='patrocinadores/documentos/'),
        ),
    ]
