# Generated by Django 6.0 on 2026-03-02 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones', '0004_patrocinador_documento'),
        ('core', '0002_alter_organizacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivocomunicacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='archivocontacto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comunicacion',
            options={'ordering': ['-fecha', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organismo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tipocomunicacion',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tipocontacto',
            options={},
        ),
        migrations.RenameField(
            model_name='comunicacion',
            old_name='observaciones',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='organizacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='organizacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organismo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organismo',
            name='organizacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocomunicacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipocomunicacion',
            name='organizacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocontacto',
            name='organizacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
            preserve_default=False,
        ),
    ]
