# Generated by Django 6.0 on 2026-03-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones', '0006_contacto_created_at'),
        ('core', '0002_alter_organizacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asociaciones.categoriainventario')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='inventario/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='asociaciones.iteminventario')),
            ],
        ),
    ]
