# Generated by Django 6.0 on 2026-03-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones', '0007_categoriainventario_iteminventario_archivoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoinventario',
            name='es_imagen',
            field=models.BooleanField(default=False),
        ),
    ]
