# Generated by Django 6.0 on 2026-03-15 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones', '0008_archivoinventario_es_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='categoriainventario',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociaciones.organizacion'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociaciones.organizacion'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociaciones.organizacion'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociaciones.organizacion'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociaciones.organizacion'),
        ),
        migrations.AlterField(
            model_name='tipocomunicacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociaciones.organizacion'),
        ),
        migrations.AlterField(
            model_name='tipocontacto',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociaciones.organizacion'),
        ),
    ]
