# Generated by Django 6.0 on 2026-03-15 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociaciones', '0009_organizacion_alter_categoriainventario_organizacion_and_more'),
        ('core', '0002_alter_organizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriainventario',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
        ),
        migrations.AlterField(
            model_name='tipocomunicacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
        ),
        migrations.AlterField(
            model_name='tipocontacto',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacion'),
        ),
        migrations.DeleteModel(
            name='Organizacion',
        ),
    ]
